# Python sekcija

Ova sveska sadrži primere koji treba da približe prirodu `reshape` funkcije i `broadcasting` ponašanje matrica. 

In [1]:
import numpy as np

## Reshape

Funkcija `reshape` se koristi za promenu dimenzije niza.

<img src ='assets/reshape.png'>

#### Primer 1.

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])

In [3]:
a.shape

(6,)

In [4]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
new_a = a.reshape(3, 2)

In [6]:
new_a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
new_a.shape

(3, 2)

Prethodni poziv `reshape` funkcije je mogao biti i `a.reshape(3, -1)` ili `a.reshape(-1, 2)`: broj `-1` koji se pojavljuje ukazuje na to da Python interpreter sam treba da izračuna ovu dimenziju na osnovu poznate. 

#### Primer 2. 

In [8]:
l = np.arange(0, 12)

In [9]:
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
l.reshape((2, -1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
l.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
l.reshape((-1, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
l.reshape((1, -1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

Dodatni primeri: [https://www.w3resource.com/numpy/manipulation/reshape.php](https://www.w3resource.com/numpy/manipulation/reshape.php)

## Broadcasting

`Broadcasting` je termin kojim se opisuje ponašanje Python interpretera kojim pokušava sa svođenjem na iste dimenzije dva ili više visedimenzionih nizova. Ovo se posebno odnosi na vektore koji imaju različite oblike.

<img src ='assets/broadcasting.png'>

#### Primer 1. 

In [14]:
a = np.array([1, 2, 3, 4])

In [15]:
a.shape

(4,)

In [16]:
a 

array([1, 2, 3, 4])

In [17]:
# ekvivalent operacije: a + np.array([5, 5, 5, 5])
a + 5

array([6, 7, 8, 9])

#### Primer 2. 

In [18]:
M = np.array([[2, 3, 0], [0, 0, 4]])

In [19]:
M.shape

(2, 3)

In [20]:
M

array([[2, 3, 0],
       [0, 0, 4]])

In [21]:
# ekvivalent operacije: M + np.array([[5, 5, 5], [5, 5, 5]])
M + 5

array([[7, 8, 5],
       [5, 5, 9]])

#### Primer 3. 

In [22]:
 M = np.array([[2, 3, 0], [0, 0, 4]])

In [23]:
M.shape

(2, 3)

In [24]:
M

array([[2, 3, 0],
       [0, 0, 4]])

In [25]:
v = np.array([1, 2, 3])

In [26]:
v.shape

(3,)

In [27]:
# ekvivalent operacije M + np.array([[1, 2, 3], [1, 2, 3]])
M + v

array([[3, 5, 3],
       [1, 2, 7]])

In [28]:
## ekvivalent operacije np.array([[1, 2, 3], [1, 2, 3]]) + M
v + M

array([[3, 5, 3],
       [1, 2, 7]])

#### Primer 4.

In [29]:
u1 = np.ones((3, 1))

In [30]:
u1.shape

(3, 1)

In [31]:
u1

array([[1.],
       [1.],
       [1.]])

In [32]:
u2 = np.array([4, 5, 6, 7])

In [33]:
u2.shape

(4,)

In [34]:
u2

array([4, 5, 6, 7])

In [35]:
u1 + u2 

array([[5., 6., 7., 8.],
       [5., 6., 7., 8.],
       [5., 6., 7., 8.]])

In [36]:
# rezultat je dimenzije 3 X 3